### ISSUE TITLE
Delta Pro value ecoflow-mqtt.0.1234.inv.cfgSlowChgWatts change back self after short period

### ISSUE THREAD

**Issue by MikeRow1972** [foxthefox/ioBroker.ecoflow-mqtt#136]
Hi, I updated to 1.0 today. Since today I can no longer write the delta Pro value ecoflow-mqtt.0.1234.inv.cfgSlowChgWatts permanently. It is reset to the old value after 1-2 seconds. A downgrade to 0.0.42 helps

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 6.0.11 
 - Node version: v20.16.0
 - Operating system: debaian 12.4

**Comment by foxthefox** [comment]
Please try version 1.0.1 from git or npm and report.

**Comment by foxthefox** [comment]
as it is confirmed to work in iobroker forum, I close this issue
