### ISSUE TITLE
mppt.dcChgCurrent don't work

### ISSUE THREAD

**Issue by planetofrock** [foxthefox/ioBroker.ecoflow-mqtt#81]
Hey.
I noticed that changing (tested with River 2 MAX and River 2 PRO) the amps in the mppt.dcChgCurrent data point doesn't work. If you enter 4, 6 or 8 amps in ioBroker, the Ecoflow does not accept it and the value automatically goes to 4A in the app, 0A is displayed in ioBroker.

Tested wirh version 0.0.29 and 0.0.21

Greetz
Pawel

**Comment by foxthefox** [comment]
Which values are possible from the App for the River2 Max and which for the River2 Pro? It might be the case that I have to adjust to the possible values.

**Comment by planetofrock** [comment]
You can set the values 0, 4 and 8 in the app. If you enter this into ioBroker, you always get back the value 0.

**Comment by foxthefox** [comment]
I think I have found the problem.
You can try the version 0.0.30 from git or npm.
Please check and report.

The value 0 is not part of the selections right now(usually this is not a valid value), as well the 6A is still available.
Can you send a screenshot from the App?

**Comment by planetofrock** [comment]
Now it works fine. Thank you. 
![Screenshot_20240525_214030_com ecoflow](https://github.com/foxthefox/ioBroker.ecoflow-mqtt/assets/71409209/3cc9c91b-0eca-42e4-bb08-37ee8b788c5d)
![Screenshot_20240525_214027_com ecoflow](https://github.com/foxthefox/ioBroker.ecoflow-mqtt/assets/71409209/17a41f56-37f0-4f0c-8d5a-07e5811b5c99)

**Comment by foxthefox** [comment]
after it is working, issue can be closed
